name: CI

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "tag=ghcr.io/borisnliscool/goeie:latest" >> $GITHUB_ENV
          else
              echo "tag=ghcr.io/borisnliscool/goeie:${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.tag }}